---   
- name: Set hostname
  nclu:
    commands:
    - add hostname {{ inventory_hostname }}
    atomic: true
   
- name: Copy SSH Key to Hosts
  authorized_key:
    user: cumulus
    state: present
    key: "{{ lookup('file', '{{ ansible_node.sshkey }}') }}"   

- name: Change Default Password
  user:
    name: cumulus
    password: "{{ my_password | password_hash('sha512') }}"