---  
- name: copy interface configs
  copy: src={{ inventory_hostname }}/interfaces dest=/etc/network/
  notify:
    - reload networking

- name: copy frr daemon configs
  copy: src={{ inventory_hostname }}/daemons dest=/etc/frr/
  notify:
    - reload frr

- name: copy frr configs
  copy: src={{ inventory_hostname }}/frr.conf dest=/etc/frr/
  notify: 
    - reload frr