---  
- name: Set hostname
  nclu:
    commands:
    - add hostname {{ inventory_hostname }}
    atomic: true

- name: Change Default Password
  user:
    name: cumulus
    password: "{{ switch_password }}"